### PR TITLE
add password reset feature

### PR DESCRIPTION
**Pull request by ozair-dev**
Your project was a good learning resource for me.
I added **password reset feature** to your project.
- password reset (navigate) button was added to the login page.
- User enters email and submits. Corresponding error or success messages are displayed accordingly.

Another issue was that user could not sign in with google. So I fixed that too.
Code formatting is a bit different due to our different editor settings.

Please review the pull request and tell me if you want me to make any changes.

### CODE REVIEW

**Comment by ozair-dev** [comment]
Run the app locally to see the changes.

**Comment by vasile-novatchii** [comment]
Hi, 
Glad to see that someone has found this demo project as learning resource. Currently I have a lot of work and don’t maintain that project. 
However I’ve checked your PR <https://github.com/Infvyr/RLibrary/pull/16> on GitHub repo. You did great job! 
I’ve noticed you selected main branch to merge your changes into. There is 1 more branch (dev branch) for developing features before pull them into main. You should make a PR into dev branch firstly. Then you check out changes running project from dev branch. If everything is OK make a PR into main ( dev -> main).
In addiction to these suggestions I also recommend you to clone repo and then go to firebase console to generate API keys. 
When you generate keys you’ll be able to paste them into .env.local file created within project src folder. 
The environment variables you can notice in here <https://github.com/Infvyr/RLibrary/blob/main/src/firebase/utils.js>. Let me know if you come across any errors etc.

**Comment by ozair-dev** [comment]
Hi, I am not very familiar with git. If I understand you correctly, u are saying that **I should make/test changes in the dev branch in my forked repository and if everything works correctly, then make a PR to your main branch from the my dev branch**. Is that right?
I actually wrote changes directly to the main branch in the cloned repo instead of writing in other branch (like dev). Is that a problem?

Also, I did setup the project on firebase and used the keys in the cloned repository.

**Comment by vasile-novatchii** [comment]
Hi, you understand correctly.
I recommend you to switch to dev branch on your machine and apply there your changes. Make sure everything works properly.
Then go to your GitHub forked repo and create new Pull Request from your dev branch to your main. 
As a result you’ll see your changes from dev branch applied to your main branch.
The idea is to make changes only to the forked project. I hope you understand my thoughts!

**Comment by ozair-dev** [comment]
Oh okay, I get it now. You want me to **make pull request to the main branch of the forked repo only and not to the original (your) repository because you no longer maintain the project**

**Comment by vasile-novatchii** [comment]
Yes. Moreover, you forked my project and it's easy for you to develop and
make pull requests directly into your repo.

**Pull request closed without merging**
